### ISSUE TITLE
board.SPI() is not found or working properly 

### ISSUE THREAD

**Issue by jpsainfeld** [ubopod/ubo-sdk#9]
python3 light_sensor_example.py 
Traceback (most recent call last):
  File "/home/pi/ubo-sdk/light_sensor/light_sensor_example.py", line 10, in <module>
    lcd = LCD()
  File "/home/pi/ubo-sdk/light_sensor/../display/lcd.py", line 98, in __init__
    spi = board.SPI()
AttributeError: module 'board' has no attribute 'SPI'

Seems like this issue happens if adafruit-blinks is not installed properly. The solution is to force reinstall this package.
fix:

pip install --force-reinstall adafruit-blinka

**Comment by ubopod** [comment]
it seems like that sometimes for some unknown reason adafruit-blinka does not get installed completely (fails during install most likely due to dependency issues). I confirm the suggested fix do work:

`pip install --force-reinstall adafruit-blinka`

I am looking into how to improve pip package install reliability with using [Poetry](https://python-poetry.org/) as a possible solution. If you have any suggestions, please do let know.

**Comment by ubopod** [comment]
I made a new issue for "improving reliability of pip packages": https://github.com/ubopod/ubo-sdk/issues/12
